---
title: "Stage 2: Draft Exploratory Analysis"
author: "Kade Aldrich"
date: '2022-11-10'
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(dplyr)
library(lubridate)
library(stringr)
library(readxl)
```

**Data Wrangling/Cleaning**

***Loading in Data***

```{r}
# changing the wd to knit the document
# comment out as needed
wd2 = "C:/Fall 22/ECNS 491/course_proj/ECNS_491_Project/Data"
setwd(wd2)

### Financial data
# loading in nasdaq data and selecting close price and date
nasdaq = read_csv("^IXIC.csv")
nasdaq = nasdaq %>%
  select(Date, Close)

# loading in dow jones data
dow = read_csv("dowjones.csv")

### Weather data
# loading in Seattle weather data
seattle = read_csv("seattle 2020-10-12 to 2022-10-12.csv")

# loading in Chicago weather data
chicago = read_csv("Chicago 2020-10-12 to 2022-10-12.csv")

# loading in New York City weather data
nyc = read_csv("New York City 2020-10-12 to 2022-10-12.csv")
```

***Joining Data Into One Tidy Data Frame***

Starting by selecting only weather variables we care about for the analysis:

-   Temperature (using average 'feels like' temperature)
-   Precipitation
-   Precipitation cover
-   Cloud cover

```{r}
### Selecting weather variables
# Seattle
seattle = seattle %>%
  select(datetime, feelslike, precip, precipcover, cloudcover)
colnames(seattle) = c("datetime", "seattle_temp", "seattle_precip", "seattle_precipcover", "seattle_cloudcover")

# Chicago
chicago = chicago %>%
  select(datetime, feelslike, precip, precipcover, cloudcover)
colnames(chicago) = c("datetime", "chicago_temp", "chicago_precip", "chicago_precipcover", "chicago_cloudcover")
# NYC
nyc = nyc %>%
  select(datetime, feelslike, precip, precipcover, cloudcover)
colnames(nyc) = c("datetime", "nyc_temp", "nyc_precip", "nyc_precipcover", "nyc_cloudcover")
```

Merging data frames together
```{r}
### creating weather df
weather = seattle %>% 
  left_join(chicago, by = "datetime")
  
weather = weather %>%
  left_join(nyc, by = "datetime")

### creating financial df
# date variables
nasdaq$Date = ymd(nasdaq$Date)
dow$date = mdy(dow$date)

# column names
colnames(nasdaq) = c("datetime", "nasdaq")
colnames(dow) = c("datetime", "dow_jones")

# merging finance
finance = nasdaq %>%
  left_join(dow, by = "datetime")

### merging weather and finance into one df
# only care about weather observations on trading days
df = finance %>%
  left_join(weather, by = "datetime")
```

**Data Visualization**

```{r}
library(ggplot2)
library(tidyverse)
library(dplyr)
rm(list = ls())
# set working directory to this file location by going to Session > Set Working Directory > To Source File Location
wd = paste(getwd(), "/Data/", sep = "")
load(paste(wd, "finalcleaned.RData", sep = ""))

ggplot(data = df, aes(x = datetime)) +
  geom_line(aes(y = seattle_temp), color = "darkmagenta") +
  geom_line(aes(y = chicago_temp), color = "darkred") +
  geom_line(aes(y = nyc_temp), color = "steelblue")

ggplot(data = df, aes(x = datetime)) +
  geom_line(aes(y = seattle_cloudcover), color = "darkmagenta") +
  geom_line(aes(y = chicago_cloudcover), color = "darkred") +
  geom_line(aes(y = nyc_cloudcover), color = "steelblue")

ggplot(data = df, aes(x = datetime)) +
  geom_line(aes(y = seattle_precipcover), color = "darkmagenta") +
  geom_line(aes(y = chicago_precipcover), color = "darkred") +
  geom_line(aes(y = nyc_precipcover), color = "steelblue")

for(i in length(df[,1])){
  df$seattle_gotprecip = ifelse(df$seattle_precip > 0,1,0)
  df$chicago_gotprecip = ifelse(df$chicago_precip > 0,1,0)
  df$nyc_gotprecip = ifelse(df$nyc_precip > 0,1,0)
}
precip_chi = mean(df$chicago_gotprecip)
precip_sea = mean(df$seattle_gotprecip) 
precip_nyc = mean(df$nyc_gotprecip)

df$chicago_macloud = 0
df$chicago_matemp = 0
df$seattle_macloud = 0
df$seattle_matemp = 0
df$nyc_macloud = 0
df$nyc_matemp = 0
i = 12
# moving average of temp and cloud cover to better see trend
for(i in 12:nrow(df)){
  df$chicago_macloud[i] = mean(df$chicago_cloudcover[i-11:i])
  df$chicago_matemp[i] = mean(df$chicago_temp[i-11:i])
  df$seattle_macloud[i] = mean(df$seattle_cloudcover[i-11:i])
  df$seattle_matemp[i] = mean(df$seattle_temp[i-11:i])
  df$nyc_macloud[i] = mean(df$nyc_cloudcover[i-11:i])
  df$nyc_matemp[i] = mean(df$nyc_temp[i-11:i])
}
df1 = df
for(i in 1:11){df1 = df1[-1,]}
# regraphes with the moving average
ggplot(data = df1, aes(x = datetime)) +
  geom_line(aes(y = seattle_matemp), color = "darkmagenta") +
  geom_line(aes(y = chicago_matemp), color = "darkred") +
  geom_line(aes(y = nyc_matemp), color = "steelblue")

ggplot(data = df1, aes(x = datetime)) +
  geom_line(aes(y = seattle_macloud), color = "darkmagenta") +
  geom_line(aes(y = chicago_macloud), color = "darkred") +
  geom_line(aes(y = nyc_macloud), color = "steelblue")

```